client/package.json
client/src/components/Reports/MemberReports/ReportInput.js
client/yarn.lock
netlify.toml

Resolves Netlify deployment issues with netlify.toml file
Cannot test until merged

Resolves Netflify Issues

---

client/package.json
client/src/components/Reports/MemberReports/MemberResponseForm.js
client/src/components/Reports/MemberReports/ReportInput.js
client/src/components/Reports/ModifyReports/CreateReport.js
client/src/components/Reports/ModifyReports/EditReport.js
client/src/components/Reports/Reports.js
client/src/components/Reports/SingleReportMember.js
client/src/components/Signup/Signup.js
client/src/index.js
client/yarn.lock

- removed graphql and apollo dependencies.
- refactored components that need state to react class components
- [**x** ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [**x**] This change requires a documentation update
- [ **x**] Incomplete/work-in-progress, PR is for discussion/feedback
I haven't - this is for discussion as I think we'll need to talk more in-depth about how the data flows. THis is my first crack at it. 
- [x ] My code follows the style guidelines of this project
- [x ] My changes generate no new warnings

Eek component refactor

---

client/src/components/Firebase/Firebase.js
client/src/components/Login/Login.js
client/src/components/Signup/Signup.js
netlify.toml

All devs able to access the production backend api when logging in or signing up

---

client/src/App.js
client/src/components/Account/Account.js
client/src/components/Firebase/Firebase.js
client/src/components/Login/Login.js
client/src/components/Onboarding/Onboarding.js

Added an Accounts page - currently the first account is hard-coded in with an email and teamId - when we get the auth fully functional, this will work dynamically
**Accounts page is not fully functional**
Ran react app locally

Mikaela currier - Added Accounts Page

---

client/public/index.html
client/src/App.js
client/src/components/Firebase/Firebase.js
client/src/components/Navigation/Navigations.js
client/src/components/Navigation/navigation.css
client/src/components/Onboarding/CreateTeam.js
client/src/components/Onboarding/JoinTeam.js
client/src/components/Onboarding/LandingPage.js
client/src/components/Onboarding/Onboarding.js
client/src/components/Onboarding/onboarding.css

Refactored the onboarding page so that the code is more readable. Also added a simple nav bar that points to account, reports, and currently both login and logout. When Auth is completed, this will show either login/logout, never both. Also, logout is not currently hooked up to anything.
Also, on the CreateTeam.js file view, I added the ability to add multiple team members by email on the same component. The component shows a running list of the emails that the user has inputted. Once the user inputs emails, they can also remove incorrect emails on this page. The input is `type=email` but currently any value is accepted. This should not happen.
Please describe the tests that you ran to verify your changes. Provide instructions so we can …

Mikaela currier

---

client/package.json
client/src/components/Firebase/Firebase.js
client/src/index.js
client/yarn.lock

Uncommented localstorage to add token when signing in/signing up

Fixing OAuth localstorage for token

---

client/src/components/Firebase/Firebase.js
client/src/components/Onboarding/CreateTeam.js
client/src/components/Onboarding/Onboarding.js
client/src/config/axiosWithAuth.js

Added authentication config, updated user when creating a team

Added authentication config, updated user when creating a team

---

client/package.json
client/src/App.js
client/src/components/Reports/MemberReports/MemberResponseForm.js
client/src/components/Reports/MemberReports/ReportInput.js
client/src/components/Reports/Reports.js
client/src/components/Reports/SingleReport.js
client/src/components/Reports/SingleReportMember.js
client/yarn.lock

will get report by id and post responses

will get report by id and post responses

---

client/src/App.js
client/src/components/Dashboard/Dashboard.js
client/src/components/Dashboard/Team.js
client/src/components/Firebase/Firebase.js
client/src/components/Reports/Reports.js

Created Dashboard and Team components

Created Dashboard and Team components

---

client/src/App.js
client/src/components/Reports/ModifyReports/CreateReport.js
client/src/components/Reports/Reports.js

Form input for creating new report - this works in state, Erin's PR will make this work with the db
local machine

create new page report pt.1

---

client/package.json
client/src/App.js
client/src/components/Account/Account.js
client/src/components/Onboarding/CreateTeam.js
client/src/components/Onboarding/JoinTeam.js
client/src/components/Onboarding/LandingPage.js
client/src/components/Onboarding/Onboarding.js
client/src/components/Reports/MangerReports/SingleReportManager.js
client/src/components/Reports/MemberReports/MemberResponseForm.js
client/src/components/Reports/MemberReports/ReportInput.js
client/src/components/Reports/ModifyReports/CreateReport.js
client/src/components/Reports/ModifyReports/EditReport.js
client/src/components/Reports/Reports.js
client/src/components/Signup/Signup.js
client/src/config/axiosWithAuth.js
client/yarn.lock

some fixes to create a report - not yet totally funcitonal. Also delete a report now works
local machine
- [] I have made corresponding changes to the documentation

Mikaela currier - updates on creating a report and deleting a report

---

client/src/App.js
client/src/components/Reports/MemberReports/MemberResponseForm.js
client/src/components/Reports/MemberReports/ReportInput.js
client/src/components/Reports/MemberReports/ReportResults.js
client/src/components/Reports/ModifyReports/CreateReport.js
client/src/components/Reports/ModifyReports/EditReport.js
client/src/components/Reports/Reports.js
client/src/components/Reports/SingleReport.js
client/src/config/axiosWithAuth.js

Team fixed CRUD operations on the front end for reports/responses

Team fixed CRUD operations on the front end for reports/responses

---

client/src/App.js
client/src/components/Reports/ModifyReports/CreateReport.js
client/src/components/Reports/ModifyReports/EditReport.js
client/src/config/axiosWithAuth.js

Updates to account now render without a refresh
Create Report button now links back to Reports page

Fixed UI bugs on Account.js and CreateReport.js

---

client/src/App.js
client/src/components/Slack/Slack.js
client/src/components/Slack/SlackRedirect.js

This will connect to Slack preferences and redirect back to a holding page that will make a GET request to our `/slack/` endpoint with the Slack code as a search param.

Connect to slack on the client

---

client/src/components/Reports/ModifyReports/CreateReport.js
client/src/components/Reports/Reports.js
client/src/components/Slack/Slack.js
client/src/components/Slack/SlackRedirect.js
client/src/config/axiosWithAuth.js

Co-authored-by: Mikaela Currier mikaela.currier@gmail.com
Connect slack channel list when creating a report and render list of reports.

connect slack channel list when creating a report

---

client/src/App.js
client/src/components/Account/Account.js
client/src/components/Dashboard/Dashboard.js
client/src/components/Dashboard/ReportsDash.js
client/src/components/Dashboard/Style/dashboard.css
client/src/components/Dashboard/Team.js
client/src/components/Navigation/Navigations.js
client/src/components/Reports/ModifyReports/CreateReport.js
client/src/components/Reports/Reports.js
client/src/components/Reports/SingleReport.js
client/src/config/axiosWithAuth.js

Co-authored-by Shaun Carmody <shaun.carmody@live.co.uk>
This is a breaking change that will re-render the page when a report is created - lots of refactoring happened today and its not yet complete, but this is how the page needs to be set up. More refactoring to follow.
- [] I have made corresponding changes to the documentation

refactoring to update reports without refreshing

---

client/src/components/Dashboard/ReportsDash.js
client/src/components/Reports/ModifyReports/CreateReport.js
client/src/components/Reports/ModifyReports/EditReport.js
client/src/components/Reports/ModifyReports/Report.css

Render reports form and populate with state when update reports form is clicked

render reports form and populate with state

---

client/src/components/Account/Account.js
client/src/components/Dashboard/ReportsDash.js
client/src/components/Reports/Reports.js
client/src/components/Reports/SingleReport.js
client/src/config/axiosWithAuth.js

A manager can archive a report - the report can then be reactivated from the manager's account page and will then show up on the reports page.
Bug: when reactivating a report, the page needs to be refreshed before it will be seen on the reports page

Archiving Reports

---

client/src/components/Onboarding/Onboarding.js
client/src/components/Reports/ModifyReports/CreateReport.js
client/src/config/axiosWithAuth.js

added a post request to the b/e email endpoint on the createTeam function on the Onboarding.js component. 

emails working

---

client/src/App.js
client/src/components/Dashboard/Dashboard.js
client/src/components/Dashboard/Team.js
client/src/components/Dashboard/User.js
client/src/config/axiosWithAuth.js

Manager can change the status of a user on their team to inactive - currently makes no changes to what the user can actually do, but its a step in the right direction

Manager can deactivate a user on team

---

client/src/components/Dashboard/ReportsDash.js
client/src/components/Reports/MemberReports/MemberResponseForm.js
client/src/components/Reports/MemberReports/ReportInput.js
client/src/components/Reports/ModifyReports/EditReport.js

- Remove input error being thrown on change
- Select current channel when modify report renders
- Render responses

Fixed various bugs

---

client/src/components/Firebase/Firebase.js
client/src/components/Login/Login.js

Firebase component now redirects to onboarding or dashboard page based on decoded token.

Login redirects working

---

client/src/components/Onboarding/JoinTeam.js
client/src/components/Onboarding/Onboarding.js

added function to "join team" button that updates a user's teamID based on join code. 

Joining team functionality fixed

---

client/src/components/Slack/Slack.js
client/src/config/axiosWithAuth.js

This will create a report on the /api/responses/:reportId endpoint

edit redirect url

---

.env
client/src/components/Dashboard/Dashboard.js
client/src/components/Dashboard/InviteUser.js
client/src/components/Firebase/Firebase.js
client/src/components/Login/Login.js
client/src/components/Onboarding/Onboarding.js
client/src/components/Slack/Slack.js
client/src/config/axiosWithAuth.js

Added a new component to Dashboard.js. Allows user to send email invite to new users. Note - this isn't blocked off from non-admin users, something to think about in the future.

New Memeber email invite component built

---

client/package.json
client/public/index.html
client/src/components/Account/Account.js
client/src/components/Dashboard/Team.js
client/src/components/Navigation/Navigations.js
client/src/config/axiosWithAuth.js
client/src/index.css
client/src/index.js
client/yarn.lock

Started with BlueprintJS. Nav and account components started
local machine

BlueprintJS startup

---

client/src/components/Navigation/Navigations.js

Toggle login and logout routes

Toggle login and logout routes

---

client/src/config/axiosWithAuth.js

change baseurl

---

client/src/components/Dashboard/ReportsDash.js
client/src/components/Dashboard/Team.js
client/src/components/Dashboard/User.js
client/src/components/Dashboard/dashboard.css
client/src/components/Reports/Reports.js
client/src/components/Reports/SingleReport.js
client/src/components/View/View.js
client/src/config/axiosWithAuth.js

Yep - the buttons on the view page are only clickable if the role from the token === admin.
Going to work on styling the reports page now

Mikaela - buttons on view only clickable for admins

---

client/package.json
client/src/components/Dashboard/Dashboard.js
client/src/components/Dashboard/InviteUser.js
client/src/components/Dashboard/Team.js
client/src/components/Dashboard/User.js
client/src/components/Dashboard/dashboard.css
client/src/components/Reports/MemberReports/ReportResults.js
client/src/components/View/View.js
client/src/components/View/view.css
client/src/config/axiosWithAuth.js
client/yarn.lock

changed layout to column, adjusted padding and margins on various components within view.js at 800px breakpoint. 

Mobile breakpoints built for views.js

---

client/src/components/Reports/MemberReports/MemberResponseForm.js
client/src/components/Reports/MemberReports/ReportResults.js

This PR will Add responseId as key to React Element

Add ID as key to React Element

---

client/src/components/Dashboard/ReportsDash.js
client/src/components/View/View.js
client/src/config/axiosWithAuth.js

cool stuff with dynamic classnames based on where the user is located. Needed for styling the reports page

dynamic classnames for reports

---

client/src/components/Dashboard/ReportsDash.js
client/src/components/Reports/Reports.js

Added Slack button even if no reports exist

Added Slack button even if no reports exist

---

client/src/components/Dashboard/User.js
client/src/components/Onboarding/CreateTeam.js
client/src/components/Onboarding/JoinTeam.js
client/src/components/Onboarding/LandingPage.js
client/src/components/Onboarding/Onboarding.js
client/src/components/Onboarding/onboarding.css
client/src/config/axiosWithAuth.js

Styled up the onboarding and added some UI error catches:
If the email sender fails, it lets the user know. User also doesn't have to add emails to create a team
If the join code doesn't exist, it lets the user know.

Mikaela - onboarding styling

---

client/src/components/Reports/ModifyReports/CreateReport.js
client/src/components/Reports/ModifyReports/Report.css

Refactored CreateReport page

---

client/src/components/DatePicker/DatePicker.js
client/src/components/Reports/MemberReports/MemberResponseForm.css
client/src/components/Reports/MemberReports/MemberResponseForm.js
client/src/components/Reports/MemberReports/ReportInput.js
client/src/components/Reports/MemberReports/ReportResults.css
client/src/components/Reports/MemberReports/ReportResults.js
client/src/index.css
client/src/index.js
client/yarn.lock

Add css reset and style report results page

add css reset and style report results page

---

client/src/components/Account/Account.js
client/src/components/Reports/ModifyReports/CreateReport.js
client/src/components/Reports/ModifyReports/EditReport.js
client/src/components/Reports/ModifyReports/Report.css

Updated edit report page and restyled create report page

 Updated edit report page and restyled create report page

---

client/src/components/Login/Login.js
client/src/components/Login/login.css
client/src/components/Reports/MemberReports/ReportResults.css
client/src/components/Reports/MemberReports/ReportResults.js

Fixed responses to block a user from responding again for the same day

 Fixed responses to block a user from responding again for the same day

---

client/src/components/Dashboard/Dashboard.js
client/src/components/Dashboard/InviteUser.js
client/src/components/Onboarding/Onboarding.js
client/src/components/Onboarding/onboarding.css

On the dashboard, there is now a modal for when an admin sends an email to a new team member for both success and failure

Mikaela - modal for success/failure sending emails

---

client/src/components/Account/Account.js
client/src/components/Account/account.css

Fixed user profile for admin and member

Fixed user profile for admin and member

---

client/src/components/Dashboard/User.js
client/src/components/Dashboard/dashboard.css

Can now deactivate user (again)

added deactivate user back in

---

client/src/components/Dashboard/Dashboard.js
client/src/components/Dashboard/Team.js
client/src/components/Dashboard/User.js
client/src/components/Onboarding/Onboarding.js
client/src/components/View/View.js

Manager can deactivate and reactivate users from the dashboard - shows as unclickable buttons for members. 
Inactive members viewable with accordion - not sure how I feel able it at the moment, open to suggestions 

Mikaela bugs - Deactivate User

---

client/src/components/Dashboard/Dashboard.js
client/src/components/Dashboard/InviteUser.js
client/src/components/Dashboard/dashboard.css
client/src/components/Navigation/Navigations.js
client/src/components/Reports/ModifyReports/CreateReport.js
client/src/components/Reports/Reports.js
client/src/components/Reports/reports.css
client/src/components/Slack/Slack.js
client/src/components/Slack/SlackRedirect.js

Various UX/UI tweaks including: 
- margin and padding on /dashboard cards
- movement of slack button to team card on dashboard
- changed slack redirect to be dynamic
- added a slack button to CreateForm.js if the page loads and the user's not permissioned
- nav bar justified as per notes

Various UX/UI fixes

---

client/src/components/DatePicker/DatePicker.js
client/src/components/Reports/MemberReports/ReportInput.js
client/src/components/Reports/MemberReports/ReportResults.css
client/src/components/Reports/MemberReports/ReportResults.js
client/src/components/Responders/Responders.js

Allows client to filter results by date and/or user.

filter results by date/user or both

---

client/src/components/Reports/MemberReports/ReportResults.css
client/src/components/Reports/MemberReports/ReportResults.js
client/src/components/Responders/Responders.js

CSS styling for Responders Component

CSS styling for Responders Component

---

client/src/components/Navigation/Navigations.js
client/src/components/Navigation/navigation.css

added a className to the nav bar links in order show them with or without text based on mediaquery

small UX fix

---

client/src/App.js
client/src/components/Dashboard/User.js
client/src/components/Navigation/Footer.js
client/src/components/Navigation/Navigations.js
client/src/components/Slack/Slack.js
client/src/components/View/View.js
client/yarn.lock

Remove slack button once authorised

Remove slack button once authorised

---

client/src/components/Onboarding/CreateTeam.js
client/src/components/Reports/ModifyReports/CreateReport.js

Create Report now much cleaner
Also can create report without changing time

tidying up create report

---

client/src/App.js
client/src/auth/NewUserRoute.js
client/src/auth/PrivateRoute.js
client/src/components/Dashboard/Dashboard.js
client/src/components/Dashboard/InviteUser.js
client/src/components/Dashboard/ReportsDash.js
client/src/components/Dashboard/Team.js
client/src/components/Dashboard/User.js
client/src/components/DatePicker/DatePicker.js
client/src/components/Firebase/Firebase.js
client/src/components/Navigation/Navigations.js
client/src/components/Onboarding/CreateTeam.js
client/src/components/Onboarding/JoinTeam.js
client/src/components/Onboarding/Onboarding.js
client/src/components/Onboarding/onboarding.css
client/src/components/Profile/Profile.js
client/src/components/Profile/profile.css
client/src/components/Reports/MemberReports/MemberResponseForm.js
client/src/components/Reports/MemberReports/ReportInput.js
client/src/components/Reports/MemberReports/ReportResults.js
client/src/components/Reports/ModifyReports/CreateReport.js
client/src/components/Reports/ModifyReports/EditReport.js
client/src/components/Reports/Reports.js
client/src/components/Reports/SingleReport.js
client/src/components/Responders/Responders.js
client/src/components/Signup/Signup.js
client/src/components/View/View.js

**so. many. comments.**
- what components do
- where parent components are when it isn't clear
- lots more
**refactors**
- pushed all renders to top of class components if they couldn't be viewed in a single page
- made functional components if class wasn't needed
- grouped imports - they were all a jumbled mess
**new stuff** 
- material-ui modals all around
- users with teamId cannot access /onboarding
**stuff I took out**
- Signup.js
- Account.js - replaced with Profile.js
- console.logs
- [xxxx] I have commented my code, particularly in hard-to-understand areas

Mikaela - Make it Pretty / Readable

---

client/src/App.js
client/src/components/Onboarding/Onboarding.js
client/src/components/Profile/Profile.js
client/src/components/Reports/ModifyReports/CreateReport.js
client/src/components/Reports/Reports.js
client/src/components/Reports/SingleReport.js

Added modals to the archive reports button, formatted a couple others. 
Added filter function to axios call for archived reports on profile.js, removed it from the render function. 

Added some modals, moved a function.

---

client/src/components/Dashboard/Dashboard.js
client/src/components/Dashboard/InviteUser.js
client/src/components/Dashboard/Team.js
client/src/components/Dashboard/User.js
client/src/components/Dashboard/dashboard.css
client/src/components/Reports/Reports.js
client/src/components/Reports/SingleReport.js
client/src/components/Reports/reports.css

Added menu drop down and refactored the team page and style changes to disabled buttons

Added menu drop down and refactored the team page

---

client/src/components/Slack/SlackRedirect.js

push user to dashboard

---

README.md
client/src/components/Navigation/Navigations.js

Updated README and navlink fix

---

client/src/components/Marketing/MarketingPage.js

Minor change to get the heroku server going when someone renders the marketing page. Hacky job to avoid having an always-on deployment. 

Added a superfluous axios call on the marketing page to wake up heroku

---

client/src/components/Marketing/MarketingPage.js

Fixed heroku poke

---

client/src/components/Marketing/MarketingPage.js

fixed heroku poke for real this time
